
'''Pulls from sample summarize_analysis output to test statistical analysis functions'''

import sys  
from pathlib import Path

# Make package importable
module_dir = Path(__file__).resolve().parents[1]

if str(module_dir) not in sys.path:
    sys.path.insert(0, str(module_dir))
import os
from tunel_quant import stats
from datetime import datetime
import pandas as pd

# Read CSV summary generated by the pipeline

summary_path = Path(__file__).resolve().parent / 'summary_MF_includeLikely_Sample.csv'

out_folder_path = Path(__file__).resolve().parent / 'output'
include_likely = True  # Set to True or False based on your test case
post_hoc = False  # Set to True or False based on your test case

summary = pd.read_csv(summary_path)
date_str = datetime.now().strftime('%Y-%m-%d')

# Perform and write statistical analysis on the summary data
anova_output_path = os.path.join(out_folder_path, f'anova_results_{date_str}.xlsx')
stats.anova_by_location(summary, post_hoc=post_hoc, include_likely=include_likely, output_path=anova_output_path)

mixed_output_path = os.path.join(out_folder_path, f'mixed_logistic_results_{date_str}.xlsx')
stats.run_mixed_logistic_by_location(summary, output_path=mixed_output_path)
